version: '3'
services:
  pg11:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_DB: delivery_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mamamama
    ports:
      - "5332:5432"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d